### ISSUE TITLE
Will there be updates for the game version 1.1.8f1 ?

### ISSUE THREAD

**Issue by TheWoolF99** [yenyang/Water_Features#9]
Will there be updates for the game version 1.1.8f1 ? 
This mod is not working in this version, when you select any building category, the interface disappears and you can't do anything else(

**Comment by yenyang** [comment]
The mod works fine with v1.1.8f1.

If you'd like general tech support, please send me a Skyve Log report, or move it log zip. It would be better to do general tech support on say the tech support channel of the Cities Skylines Modding discord instead of a github issue.
